version: '3'

services:
  boot_app:
    container_name: boot_app
    image: saulomcchelsom/boot_app:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge